### ISSUE TITLE
Error when running run_pyclone_vi_example1.sh

### ISSUE THREAD

**Issue by nakane-scc** [ncsa/phyloflow#49]
After installing miniwdl, I ran run_pyclone_vi_example1.sh and got the following error message. How should I deal with this?

Traceback (most recent call last):
  File "/home/miniconda3/bin/miniwdl", line 10, in <module>
    sys.exit(main())
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/CLI.py", line 73, in main
    runner(**vars(args))
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/CLI.py", line 737, in runner
    target, input_env, input_json = runner_input(
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/CLI.py", line 1013, in runner_input
    v = runner_input_value(s_value, decl.type, downloadable, root)
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/CLI.py", line 1176, in runner_input_value
    s_value = validate_input_path(os.path.expanduser(s_value), directory, downloadable, root)
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/CLI.py", line 1222, in validate_input_path
    if downloadable and downloadable(path, directory):
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/CLI.py", line 744, in <lambda>
    downloadable=lambda fn, is_dir: runtime.download.able(cfg, fn, directory=is_dir),
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/runtime/download.py", line 68, in able
    return bool(uri and _downloader(cfg, uri, directory=directory) is not None)
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/runtime/download.py", line 56, in _downloader
    _load(cfg)
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/runtime/download.py", line 45, in _load
    for plugin_name, plugin_fn in config.load_plugins(cfg, "file_download"):
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/runtime/config.py", line 395, in load_plugins
    yield from (
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/runtime/config.py", line 395, in <genexpr>
    yield from (
  File "/home/miniconda3/lib/python3.9/site-packages/WDL/runtime/config.py", line 386, in load_all_plugins
    importlib_metadata.entry_points().get(f"miniwdl.plugin.{group}", [])
AttributeError: 'EntryPoints' object has no attribute 'get'

**Comment by pgroves** [comment]
Hi,

Can you try to build the docker image from the same version of the code you are trying to run? Just run the script at 
```https://github.com/ncsa/phyloflow/blob/master/pyclone_vi/docker/build_pyclone_vi_container.sh```
and try again.

I've been away from this project for several months and I'm not sure if the published docker images are up to date with the wdl tasks in the code base.

If that doesn't work, we can dig deeper.

-Peter

**Comment by nakane-scc** [comment]
Thank you for your response.

When you run the "build_pyclone_vi_container.sh" script, you will see the following error message

failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2218653516/Dockerfile-pyclone-vi: no such file or directory.

I have Ubuntu 20.04LTS installed on WSL2, could this environment be causing the error?

**Comment by ChuanyiZ** [comment]
Hi,
Could you try setting these environment variables in the terminal before running `build_pyclone_vi_container.sh`?
``` bash
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
```
